//FETCHING
export const SET_FETCH_LOADING = 'SET_FETCH_LOADING';
export const SET_FETCH_READY = 'SET_FETCH_READY';

//FILTERS
export const FILTER_BY_PROFESSION = 'FILTER_BY_PROFESSION';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const SET_AGE_SELECTED = 'SET_AGE_SELECTED';
export const SET_WEIGHT_SELECTED = 'SET_WEIGHT_SELECTED';
export const SET_HEIGHT_SELECTED = 'SET_HEIGHT_SELECTED';
export const APPLY_FILTERS = 'APPLY_FILTERS';
export const SHOW_HIDE_DETAILS = 'SHOW_HIDE_DETAILS';

//INHABITANTS
export const INHABITANTS_LOAD_DATA = 'INHABITANTS_LOAD_DATA';
export const INHABITANTS_LOAD_ERROR = 'INHABITANTS_LOAD_ERROR';
export const INHABITANTS_LOAD_FILTERS = 'INHABITANTS_LOAD_FILTERS';
